### ISSUE TITLE
NMT CSI Server is down

### ISSUE THREAD

**Issue by emjhay2004** [vaidyasr/nmtcsi#1]
![image](https://user-images.githubusercontent.com/58817065/91813870-e5d4c500-ec65-11ea-94ad-84a5657de4bc.png)

There is something wrong with the xml, Repository, Packages and Downloads links for the NMT CSI.

Hopefully the NMT CSI can be updated to a working server like here in github for easy updating if something needs to be updated.

**Comment by vaidyasr** [comment]
The repository has been changed to github. Hope it should work fine.
